#!/usr/bin/env bash
#FUNCIONES
run_who() {
	who
}
run_ps() {
	ps
}
run_df() {
	df
}
run_du() {
	du
}
run_grep() {
	grep "$1" "$2"
}
run_lp() {
	lp
}
run_ls() {
	ls "$1"
}
run_cat() {
	cat "$1"
}
#FUNCIONES
# Menú principal
while true; do
	echo "1. who"
	echo "2. ps"
	echo "3. df"
	echo "4. du"
	echo "5. grep"
	echo "6. lp"
	echo "7. ls"
	echo "8. cat"
	echo "9. Salir"

	read -p "Seleccione una opción: " option

	case $option in
	1) run_who ;;
	2) run_ps ;;
	3) run_df ;;
	4) run_du ;;
	5)
		read -p "Ingrese el patrón para buscar: " patron
		read -p "Ingresa el archivo a analizar: " archivo
		run_grep "$patron" "$archivo"
		;;
	6) run_lp ;;
	7)
		read -p "Ingrese las opciones para ls (si las hay): " ls_options
		run_ls "$ls_options"
		;;
	8)
		read -p "Ingrese el nombre del archivo para mostrar: " file
		run_cat "$file"
		;;
	9)
		echo "¡Hasta luego!"
		break
		exit
		;;
	*) echo "Opción no válida. Inténtelo de nuevo." ;;
	esac

	echo ""
done
